# Run: sourcekitten doc --spm --module-name BitByteData > docs.json
sourcekitten_sourcefile: docs.json
clean: false
author: Timofey Solomko
module: BitByteData
module_version: 2.0.3
copyright: '© 2023 Timofey Solomko'
readme: README.md
github_url: https://github.com/tsolomko/BitByteData
github_file_prefix: https://github.com/tsolomko/BitByteData/tree/2.0.3
theme: fullwidth

custom_categories:
    - name: Reading bytes
      children:
      - ByteReader
      - LittleEndianByteReader
      - BigEndianByteReader
    - name: Reading bits (and bytes)
      children:
      - BitReader
      - LsbBitReader
      - MsbBitReader
    - name: Writing bits (and bytes)
      children:
      - BitWriter
      - LsbBitWriter
      - MsbBitWriter
